
//
// colors/LunaColors.swift
//

// Do not edit directly
// Generated on Mon, 26 Jul 2021 14:20:43 GMT


import UIKit

public class LnLunaColors {
    public static let colorMonochromeBlack = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    public static let colorMonochromeDark = UIColor(red: 0.251, green: 0.251, blue: 0.251, alpha: 1)
    public static let colorMonochromeDarkRgb = UIColor(red: 0.251, green: 0.251, blue: 0.251, alpha: 1)
    public static let colorMonochromeDarker = UIColor(red: 0.149, green: 0.149, blue: 0.149, alpha: 1)
    public static let colorMonochromeDarkerRgb = UIColor(red: 0.149, green: 0.149, blue: 0.149, alpha: 1)
    public static let colorMonochromeGrey = UIColor(red: 0.549, green: 0.549, blue: 0.549, alpha: 1) /* deprecated */
    public static let colorMonochromeGreyDark = UIColor(red: 0.251, green: 0.251, blue: 0.251, alpha: 1) /* deprecated */
    public static let colorMonochromeGreyDarker = UIColor(red: 0.149, green: 0.149, blue: 0.149, alpha: 1) /* deprecated */
    public static let colorMonochromeGreyLight = UIColor(red: 0.847, green: 0.847, blue: 0.847, alpha: 1) /* deprecated */
    public static let colorMonochromeGreyVLight = UIColor(red: 0.949, green: 0.949, blue: 0.949, alpha: 1) /* deprecated */
    public static let colorMonochromeLight = UIColor(red: 0.847, green: 0.847, blue: 0.847, alpha: 1)
    public static let colorMonochromeLightRgb = UIColor(red: 0.847, green: 0.847, blue: 0.847, alpha: 1)
    public static let colorMonochromeLighter = UIColor(red: 0.949, green: 0.949, blue: 0.949, alpha: 1)
    public static let colorMonochromeLighterRgb = UIColor(red: 0.949, green: 0.949, blue: 0.949, alpha: 1)
    public static let colorMonochromeMedium = UIColor(red: 0.451, green: 0.451, blue: 0.451, alpha: 1)
    public static let colorMonochromeMediumRgb = UIColor(red: 0.451, green: 0.451, blue: 0.451, alpha: 1)
    public static let colorMonochromeWhite = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1)
    public static let colorPaletteBlack = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    public static let colorPaletteBlue = UIColor(red: 0.098, green: 0.463, blue: 0.824, alpha: 1)
    public static let colorPaletteBlue10 = UIColor(red: 0.910, green: 0.945, blue: 0.984, alpha: 1)
    public static let colorPaletteBlue100 = UIColor(red: 0.055, green: 0.255, blue: 0.455, alpha: 1)
    public static let colorPaletteBlue20 = UIColor(red: 0.749, green: 0.851, blue: 0.949, alpha: 1)
    public static let colorPaletteBlue30 = UIColor(red: 0.584, green: 0.753, blue: 0.918, alpha: 1)
    public static let colorPaletteBlue40 = UIColor(red: 0.424, green: 0.655, blue: 0.886, alpha: 1)
    public static let colorPaletteBlue50 = UIColor(red: 0.259, green: 0.561, blue: 0.855, alpha: 1)
    public static let colorPaletteBlue60 = UIColor(red: 0.098, green: 0.463, blue: 0.824, alpha: 1)
    public static let colorPaletteBlue70 = UIColor(red: 0.086, green: 0.412, blue: 0.729, alpha: 1)
    public static let colorPaletteBlue80 = UIColor(red: 0.075, green: 0.361, blue: 0.639, alpha: 1)
    public static let colorPaletteBlue90 = UIColor(red: 0.067, green: 0.306, blue: 0.545, alpha: 1)
    public static let colorPaletteBrand1 = UIColor(red: 0.098, green: 0.463, blue: 0.824, alpha: 1)
    public static let colorPaletteBrand1Highlight = UIColor(red: 0.075, green: 0.361, blue: 0.639, alpha: 1)
    public static let colorPaletteBrand2 = UIColor(red: 0.180, green: 0.490, blue: 0.196, alpha: 1)
    public static let colorPaletteBrand2Highlight = UIColor(red: 0.141, green: 0.380, blue: 0.153, alpha: 1)
    public static let colorPaletteGreen = UIColor(red: 0.180, green: 0.490, blue: 0.196, alpha: 1)
    public static let colorPaletteGreen10 = UIColor(red: 0.918, green: 0.949, blue: 0.922, alpha: 1)
    public static let colorPaletteGreen100 = UIColor(red: 0.098, green: 0.271, blue: 0.110, alpha: 1)
    public static let colorPaletteGreen20 = UIColor(red: 0.773, green: 0.859, blue: 0.776, alpha: 1)
    public static let colorPaletteGreen30 = UIColor(red: 0.624, green: 0.765, blue: 0.631, alpha: 1)
    public static let colorPaletteGreen40 = UIColor(red: 0.475, green: 0.675, blue: 0.486, alpha: 1)
    public static let colorPaletteGreen50 = UIColor(red: 0.329, green: 0.580, blue: 0.341, alpha: 1)
    public static let colorPaletteGreen60 = UIColor(red: 0.180, green: 0.490, blue: 0.196, alpha: 1)
    public static let colorPaletteGreen70 = UIColor(red: 0.161, green: 0.435, blue: 0.173, alpha: 1)
    public static let colorPaletteGreen80 = UIColor(red: 0.141, green: 0.380, blue: 0.153, alpha: 1)
    public static let colorPaletteGreen90 = UIColor(red: 0.122, green: 0.325, blue: 0.129, alpha: 1)
    public static let colorPaletteGrey10 = UIColor(red: 0.949, green: 0.949, blue: 0.949, alpha: 1)
    public static let colorPaletteGrey100 = UIColor(red: 0.051, green: 0.051, blue: 0.051, alpha: 1)
    public static let colorPaletteGrey20 = UIColor(red: 0.847, green: 0.847, blue: 0.847, alpha: 1)
    public static let colorPaletteGrey30 = UIColor(red: 0.749, green: 0.749, blue: 0.749, alpha: 1)
    public static let colorPaletteGrey40 = UIColor(red: 0.651, green: 0.651, blue: 0.651, alpha: 1)
    public static let colorPaletteGrey50 = UIColor(red: 0.549, green: 0.549, blue: 0.549, alpha: 1)
    public static let colorPaletteGrey60 = UIColor(red: 0.451, green: 0.451, blue: 0.451, alpha: 1)
    public static let colorPaletteGrey70 = UIColor(red: 0.349, green: 0.349, blue: 0.349, alpha: 1)
    public static let colorPaletteGrey80 = UIColor(red: 0.251, green: 0.251, blue: 0.251, alpha: 1)
    public static let colorPaletteGrey90 = UIColor(red: 0.149, green: 0.149, blue: 0.149, alpha: 1)
    public static let colorPaletteRed = UIColor(red: 0.835, green: 0.000, blue: 0.000, alpha: 1)
    public static let colorPaletteRed10 = UIColor(red: 0.984, green: 0.902, blue: 0.902, alpha: 1)
    public static let colorPaletteRed100 = UIColor(red: 0.459, green: 0.000, blue: 0.000, alpha: 1)
    public static let colorPaletteRed20 = UIColor(red: 0.953, green: 0.722, blue: 0.722, alpha: 1)
    public static let colorPaletteRed30 = UIColor(red: 0.925, green: 0.541, blue: 0.541, alpha: 1)
    public static let colorPaletteRed40 = UIColor(red: 0.894, green: 0.361, blue: 0.361, alpha: 1)
    public static let colorPaletteRed50 = UIColor(red: 0.867, green: 0.180, blue: 0.180, alpha: 1)
    public static let colorPaletteRed60 = UIColor(red: 0.835, green: 0.000, blue: 0.000, alpha: 1)
    public static let colorPaletteRed70 = UIColor(red: 0.741, green: 0.000, blue: 0.000, alpha: 1)
    public static let colorPaletteRed80 = UIColor(red: 0.647, green: 0.000, blue: 0.000, alpha: 1)
    public static let colorPaletteRed90 = UIColor(red: 0.553, green: 0.000, blue: 0.000, alpha: 1)
    public static let colorPaletteWhite = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1)
    public static let colorPaletteYellow = UIColor(red: 1.000, green: 0.839, blue: 0.000, alpha: 1)
    public static let colorPaletteYellow10 = UIColor(red: 1.000, green: 0.984, blue: 0.902, alpha: 1)
    public static let colorPaletteYellow100 = UIColor(red: 0.549, green: 0.463, blue: 0.000, alpha: 1)
    public static let colorPaletteYellow20 = UIColor(red: 1.000, green: 0.957, blue: 0.722, alpha: 1)
    public static let colorPaletteYellow30 = UIColor(red: 1.000, green: 0.925, blue: 0.541, alpha: 1)
    public static let colorPaletteYellow40 = UIColor(red: 1.000, green: 0.898, blue: 0.361, alpha: 1)
    public static let colorPaletteYellow50 = UIColor(red: 1.000, green: 0.867, blue: 0.180, alpha: 1)
    public static let colorPaletteYellow60 = UIColor(red: 1.000, green: 0.839, blue: 0.000, alpha: 1)
    public static let colorPaletteYellow70 = UIColor(red: 0.886, green: 0.745, blue: 0.000, alpha: 1)
    public static let colorPaletteYellow80 = UIColor(red: 0.776, green: 0.651, blue: 0.000, alpha: 1)
    public static let colorPaletteYellow90 = UIColor(red: 0.663, green: 0.557, blue: 0.000, alpha: 1)
    public static let colorPromotionNewBase = UIColor(red: 0.098, green: 0.463, blue: 0.824, alpha: 1)
    public static let colorPromotionNewDark = UIColor(red: 0.086, green: 0.412, blue: 0.729, alpha: 1)
    public static let colorPromotionNewDarker = UIColor(red: 0.075, green: 0.361, blue: 0.639, alpha: 1)
    public static let colorPromotionNewDarkest = UIColor(red: 0.067, green: 0.306, blue: 0.545, alpha: 1)
    public static let colorPromotionNewLight = UIColor(red: 0.259, green: 0.561, blue: 0.855, alpha: 1)
    public static let colorPromotionNewLighter = UIColor(red: 0.584, green: 0.753, blue: 0.918, alpha: 1)
    public static let colorPromotionNewLightest = UIColor(red: 0.910, green: 0.945, blue: 0.984, alpha: 1)
    public static let colorPromotionSaleBase = UIColor(red: 0.835, green: 0.000, blue: 0.000, alpha: 1)
    public static let colorPromotionSaleDark = UIColor(red: 0.741, green: 0.000, blue: 0.000, alpha: 1)
    public static let colorPromotionSaleDarker = UIColor(red: 0.647, green: 0.000, blue: 0.000, alpha: 1)
    public static let colorPromotionSaleDarkest = UIColor(red: 0.553, green: 0.000, blue: 0.000, alpha: 1)
    public static let colorPromotionSaleLight = UIColor(red: 0.867, green: 0.180, blue: 0.180, alpha: 1)
    public static let colorPromotionSaleLighter = UIColor(red: 0.925, green: 0.541, blue: 0.541, alpha: 1)
    public static let colorPromotionSaleLightest = UIColor(red: 0.984, green: 0.902, blue: 0.902, alpha: 1)
    public static let colorSchemeBrand1Base = UIColor(red: 0.251, green: 0.251, blue: 0.251, alpha: 1)
    public static let colorSchemeBrand1Highlight = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    public static let colorSchemeBrand1OnBase = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1)
    public static let colorSchemeBrand1OnHighlight = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1)
    public static let colorSchemeBrand2Base = UIColor(red: 0.251, green: 0.251, blue: 0.251, alpha: 1)
    public static let colorSchemeBrand2Highlight = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    public static let colorSchemeBrand2OnBase = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1)
    public static let colorSchemeBrand2OnHighlight = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1)
    public static let colorSchemeDarkBase = UIColor(red: 0.251, green: 0.251, blue: 0.251, alpha: 1)
    public static let colorSchemeDarkHighlight = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    public static let colorSchemeDarkOnBase = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1)
    public static let colorSchemeDarkOnHighlight = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1)
    public static let colorSchemeLightBase = UIColor(red: 0.949, green: 0.949, blue: 0.949, alpha: 1)
    public static let colorSchemeLightHighlight = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1)
    public static let colorSchemeLightOnBase = UIColor(red: 0.251, green: 0.251, blue: 0.251, alpha: 1)
    public static let colorSchemeLightOnHighlight = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    public static let colorSemanticErrorBase = UIColor(red: 0.835, green: 0.000, blue: 0.000, alpha: 1)
    public static let colorSemanticErrorDark = UIColor(red: 0.741, green: 0.000, blue: 0.000, alpha: 1)
    public static let colorSemanticErrorDarker = UIColor(red: 0.647, green: 0.000, blue: 0.000, alpha: 1)
    public static let colorSemanticErrorLight = UIColor(red: 0.867, green: 0.180, blue: 0.180, alpha: 1)
    public static let colorSemanticErrorLighter = UIColor(red: 0.984, green: 0.902, blue: 0.902, alpha: 1)
    public static let colorSemanticErrorText = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1) /* The default accessible text on the base value */
    public static let colorSemanticInfoBase = UIColor(red: 0.098, green: 0.463, blue: 0.824, alpha: 1)
    public static let colorSemanticInfoDark = UIColor(red: 0.086, green: 0.412, blue: 0.729, alpha: 1)
    public static let colorSemanticInfoDarker = UIColor(red: 0.075, green: 0.361, blue: 0.639, alpha: 1)
    public static let colorSemanticInfoLight = UIColor(red: 0.259, green: 0.561, blue: 0.855, alpha: 1)
    public static let colorSemanticInfoLighter = UIColor(red: 0.910, green: 0.945, blue: 0.984, alpha: 1)
    public static let colorSemanticInfoText = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1) /* The default accessible text on the base value */
    public static let colorSemanticSuccessBase = UIColor(red: 0.180, green: 0.490, blue: 0.196, alpha: 1)
    public static let colorSemanticSuccessDark = UIColor(red: 0.161, green: 0.435, blue: 0.173, alpha: 1)
    public static let colorSemanticSuccessDarker = UIColor(red: 0.141, green: 0.380, blue: 0.153, alpha: 1)
    public static let colorSemanticSuccessLight = UIColor(red: 0.329, green: 0.580, blue: 0.341, alpha: 1)
    public static let colorSemanticSuccessLighter = UIColor(red: 0.918, green: 0.949, blue: 0.922, alpha: 1)
    public static let colorSemanticSuccessText = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1) /* The default accessible text on the base value */
    public static let colorSemanticWarningBase = UIColor(red: 1.000, green: 0.839, blue: 0.000, alpha: 1)
    public static let colorSemanticWarningDark = UIColor(red: 0.886, green: 0.745, blue: 0.000, alpha: 1)
    public static let colorSemanticWarningDarker = UIColor(red: 0.776, green: 0.651, blue: 0.000, alpha: 1)
    public static let colorSemanticWarningLight = UIColor(red: 1.000, green: 0.867, blue: 0.180, alpha: 1)
    public static let colorSemanticWarningLighter = UIColor(red: 1.000, green: 0.984, blue: 0.902, alpha: 1)
    public static let colorSemanticWarningText = UIColor(red: 0.251, green: 0.251, blue: 0.251, alpha: 1) /* The default accessible text on the base value */
    public static let fontStackBody1FontFamily = system, -apple-system, ".SFNSText-Regular", "San Francisco", "Roboto", "Oxygen-Sans", "Ubuntu", "Cantarell", "Segoe UI", "Helvetica Neue", "Lucida Grande", sans-serif
    public static let fontStackBody1FontSize = 16
    public static let fontStackBody1FontWeight = 400
    public static let fontStackBody1LineHeight = 24
    public static let fontStackBody2FontFamily = system, -apple-system, ".SFNSText-Regular", "San Francisco", "Roboto", "Oxygen-Sans", "Ubuntu", "Cantarell", "Segoe UI", "Helvetica Neue", "Lucida Grande", sans-serif
    public static let fontStackBody2FontSize = 18
    public static let fontStackBody2FontWeight = 400
    public static let fontStackBody2LineHeight = 26
    public static let fontStackButtonFontFamily = system, -apple-system, ".SFNSText-Regular", "San Francisco", "Roboto", "Oxygen-Sans", "Ubuntu", "Cantarell", "Segoe UI", "Helvetica Neue", "Lucida Grande", sans-serif
    public static let fontStackButtonFontSize = 16
    public static let fontStackButtonFontWeight = 700
    public static let fontStackButtonLineHeight = 24
    public static let fontStackCaptionFontFamily = system, -apple-system, ".SFNSText-Regular", "San Francisco", "Roboto", "Oxygen-Sans", "Ubuntu", "Cantarell", "Segoe UI", "Helvetica Neue", "Lucida Grande", sans-serif
    public static let fontStackCaptionFontSize = 14
    public static let fontStackCaptionFontWeight = 400
    public static let fontStackCaptionLineHeight = 22
    public static let fontStackDisplay1FontFamily = system, -apple-system, ".SFNSText-Regular", "San Francisco", "Roboto", "Oxygen-Sans", "Ubuntu", "Cantarell", "Segoe UI", "Helvetica Neue", "Lucida Grande", sans-serif
    public static let fontStackDisplay1FontSize = 18
    public static let fontStackDisplay1FontWeight = 700
    public static let fontStackDisplay1LineHeight = 26
    public static let fontStackDisplay2FontFamily = system, -apple-system, ".SFNSText-Regular", "San Francisco", "Roboto", "Oxygen-Sans", "Ubuntu", "Cantarell", "Segoe UI", "Helvetica Neue", "Lucida Grande", sans-serif
    public static let fontStackDisplay2FontSize = 20
    public static let fontStackDisplay2FontWeight = 700
    public static let fontStackDisplay2LineHeight = 26
    public static let fontStackDisplay3FontFamily = system, -apple-system, ".SFNSText-Regular", "San Francisco", "Roboto", "Oxygen-Sans", "Ubuntu", "Cantarell", "Segoe UI", "Helvetica Neue", "Lucida Grande", sans-serif
    public static let fontStackDisplay3FontSize = 24
    public static let fontStackDisplay3FontWeight = 700
    public static let fontStackDisplay3LineHeight = 32
    public static let fontStackDisplay4FontFamily = system, -apple-system, ".SFNSText-Regular", "San Francisco", "Roboto", "Oxygen-Sans", "Ubuntu", "Cantarell", "Segoe UI", "Helvetica Neue", "Lucida Grande", sans-serif
    public static let fontStackDisplay4FontSize = 30
    public static let fontStackDisplay4FontWeight = 700
    public static let fontStackDisplay4LineHeight = 40
    public static let fontStackDisplay5FontFamily = system, -apple-system, ".SFNSText-Regular", "San Francisco", "Roboto", "Oxygen-Sans", "Ubuntu", "Cantarell", "Segoe UI", "Helvetica Neue", "Lucida Grande", sans-serif
    public static let fontStackDisplay5FontSize = 38
    public static let fontStackDisplay5FontWeight = 700
    public static let fontStackDisplay5LineHeight = 50
    public static let fontStackDisplay6FontFamily = system, -apple-system, ".SFNSText-Regular", "San Francisco", "Roboto", "Oxygen-Sans", "Ubuntu", "Cantarell", "Segoe UI", "Helvetica Neue", "Lucida Grande", sans-serif
    public static let fontStackDisplay6FontSize = 48
    public static let fontStackDisplay6FontWeight = 700
    public static let fontStackDisplay6LineHeight = 62
    public static let fontStackDisplay7FontFamily = system, -apple-system, ".SFNSText-Regular", "San Francisco", "Roboto", "Oxygen-Sans", "Ubuntu", "Cantarell", "Segoe UI", "Helvetica Neue", "Lucida Grande", sans-serif
    public static let fontStackDisplay7FontSize = 60
    public static let fontStackDisplay7FontWeight = 700
    public static let fontStackDisplay7LineHeight = 76
    public static let fontStackLabel1FontFamily = system, -apple-system, ".SFNSText-Regular", "San Francisco", "Roboto", "Oxygen-Sans", "Ubuntu", "Cantarell", "Segoe UI", "Helvetica Neue", "Lucida Grande", sans-serif
    public static let fontStackLabel1FontSize = 16
    public static let fontStackLabel1FontWeight = 700
    public static let fontStackLabel1LineHeight = 24
    public static let fontStackLabel2FontFamily = system, -apple-system, ".SFNSText-Regular", "San Francisco", "Roboto", "Oxygen-Sans", "Ubuntu", "Cantarell", "Segoe UI", "Helvetica Neue", "Lucida Grande", sans-serif
    public static let fontStackLabel2FontSize = 16
    public static let fontStackLabel2FontWeight = 700
    public static let fontStackLabel2LineHeight = 24
    public static let modeDarkBackground = UIColor(red: 0.149, green: 0.149, blue: 0.149, alpha: 1)
    public static let modeDarkBase = UIColor(red: 0.949, green: 0.949, blue: 0.949, alpha: 1)
    public static let modeDarkBaseInverse = UIColor(red: 0.251, green: 0.251, blue: 0.251, alpha: 1)
    public static let modeDarkBorder = UIColor(red: 0.251, green: 0.251, blue: 0.251, alpha: 1)
    public static let modeDarkBorderInteractive = UIColor(red: 0.451, green: 0.451, blue: 0.451, alpha: 1)
    public static let modeDarkBorderInteractiveHighlight = UIColor(red: 0.949, green: 0.949, blue: 0.949, alpha: 1)
    public static let modeDarkFooterBackground = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1)
    public static let modeDarkFooterText = UIColor(red: 0.251, green: 0.251, blue: 0.251, alpha: 1)
    public static let modeDarkForeground = UIColor(red: 0.149, green: 0.149, blue: 0.149, alpha: 1)
    public static let modeDarkHeaderBackground = UIColor(red: 0.149, green: 0.149, blue: 0.149, alpha: 1)
    public static let modeDarkHeaderText = UIColor(red: 0.949, green: 0.949, blue: 0.949, alpha: 1)
    public static let modeDarkHighlight = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1)
    public static let modeDarkHighlightInverse = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    public static let modeDefaultBackground = UIColor(red: 0.949, green: 0.949, blue: 0.949, alpha: 1) /* default website background */
    public static let modeDefaultBase = UIColor(red: 0.251, green: 0.251, blue: 0.251, alpha: 1) /* base text colour on default bg */
    public static let modeDefaultBaseInverse = UIColor(red: 0.251, green: 0.251, blue: 0.251, alpha: 1) /* base text colour on default foreground */
    public static let modeDefaultBorder = UIColor(red: 0.847, green: 0.847, blue: 0.847, alpha: 1)
    public static let modeDefaultBorderInteractive = UIColor(red: 0.451, green: 0.451, blue: 0.451, alpha: 1)
    public static let modeDefaultBorderInteractiveHighlight = UIColor(red: 0.949, green: 0.949, blue: 0.949, alpha: 1)
    public static let modeDefaultFooterBackground = UIColor(red: 0.149, green: 0.149, blue: 0.149, alpha: 1)
    public static let modeDefaultFooterText = UIColor(red: 0.949, green: 0.949, blue: 0.949, alpha: 1)
    public static let modeDefaultForeground = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1) /* default background that are given to luna components */
    public static let modeDefaultHeaderBackground = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1)
    public static let modeDefaultHeaderText = UIColor(red: 0.251, green: 0.251, blue: 0.251, alpha: 1)
    public static let modeDefaultHighlight = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    public static let modeDefaultHighlightInverse = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    public static let modifierBorderInteractiveWidth = 1px /* generally used for interactive components such as input fields */
    public static let modifierBorderRadius = 2px
    public static let modifierBorderRadiusLarge = 4px
    public static let modifierBorderWidth = 1px
    public static let modifierBorderWidthLarge = 2px
    public static let modifierButtonBorder = 2px
    public static let modifierFocusRingColor = UIColor(red: 0.098, green: 0.463, blue: 0.824, alpha: 1)
    public static let modifierFocusRingFocusWidth = 3px
    public static let modifierFooterBackground = UIColor(red: 0.251, green: 0.251, blue: 0.251, alpha: 1)
    public static let modifierFooterText = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1)
    public static let modifierGlobalBarHeight = 36px
    public static let modifierHeaderBackground = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1)
    public static let modifierTransitionDuration = 0.2s
    public static let modifierTransitionDurationLong = 0.4s
    public static let modifierTransitionTimingFunctionDefault = ease-out
    public static let opacityBackground = 0.06
    public static let opacityDefault = 0.7
    public static let opacityDisabled = 0.35
    public static let opacityLight = 0.15
    public static let overlayColor = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    public static let overlayOpacity = 0.7
    public static let spaceBaselineCondensed = 4
    public static let spaceBaselineGrid = 8
    public static let spaceBreakpointsExtraExtraLarge = 1800
    public static let spaceBreakpointsExtraExtraSmall = 480
    public static let spaceBreakpointsExtraLarge = 1400
    public static let spaceBreakpointsExtraSmall = 600
    public static let spaceBreakpointsLarge = 1200
    public static let spaceBreakpointsMedium = 960
    public static let spaceBreakpointsSmall = 720
    public static let spaceFixedWidthExtraSmall = 800
    public static let spaceFixedWidthLarge = 1800
    public static let spaceFixedWidthMedium = 1440
    public static let spaceFixedWidthSmall = 1280
    public static let spaceSizeLarge = 80
    public static let spaceSizeMedium = 48
    public static let spaceSizeSmall = 24
    public static let spaceSpacingDefault = 8
    public static let spaceSpacingExtraLarge = 32
    public static let spaceSpacingExtraSmall = 4
    public static let spaceSpacingHalf = 4
    public static let spaceSpacingLarge = 24
    public static let spaceSpacingMedium = 16
    public static let spaceSpacingSmall = 8
    public static let spaceSpacingX1 = 8
    public static let spaceSpacingX10 = 80
    public static let spaceSpacingX2 = 16
    public static let spaceSpacingX3 = 24
    public static let spaceSpacingX4 = 32
    public static let spaceSpacingX5 = 40
    public static let spaceSpacingX6 = 48
    public static let spaceSpacingX7 = 56
    public static let spaceSpacingX8 = 64
    public static let spaceSpacingX9 = 72
    public static let surfaceDarkBackground = UIColor(red: 0.149, green: 0.149, blue: 0.149, alpha: 1)
    public static let surfaceDarkBase = UIColor(red: 0.949, green: 0.949, blue: 0.949, alpha: 1) /* base text colour on default bg */
    public static let surfaceDarkBorder = UIColor(red: 0.251, green: 0.251, blue: 0.251, alpha: 1)
    public static let surfaceDarkHighlight = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1)
    public static let surfaceDarkInteractive = UIColor(red: 0.451, green: 0.451, blue: 0.451, alpha: 1)
    public static let surfaceDarkInteractiveHover = UIColor(red: 0.251, green: 0.251, blue: 0.251, alpha: 1)
    public static let surfaceGreyBackground = UIColor(red: 0.149, green: 0.149, blue: 0.149, alpha: 1)
    public static let surfaceGreyBase = UIColor(red: 0.949, green: 0.949, blue: 0.949, alpha: 1) /* base text colour on default bg */
    public static let surfaceGreyBorder = UIColor(red: 0.251, green: 0.251, blue: 0.251, alpha: 1)
    public static let surfaceGreyHighlight = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    public static let surfaceLightBackground = UIColor(red: 0.949, green: 0.949, blue: 0.949, alpha: 1) /* surface colour most likely to be used as a background */
    public static let surfaceLightBase = UIColor(red: 0.251, green: 0.251, blue: 0.251, alpha: 1) /* base text colour on default bg */
    public static let surfaceLightBorder = UIColor(red: 0.847, green: 0.847, blue: 0.847, alpha: 1)
    public static let surfaceLightHighlight = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    public static let surfaceLightInteractive = UIColor(red: 0.451, green: 0.451, blue: 0.451, alpha: 1)
    public static let surfaceLightInteractiveHover = UIColor(red: 0.949, green: 0.949, blue: 0.949, alpha: 1)
    public static let surfaceWhiteBackground = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1)
    public static let surfaceWhiteBase = UIColor(red: 0.251, green: 0.251, blue: 0.251, alpha: 1)
    public static let surfaceWhiteBorder = UIColor(red: 0.847, green: 0.847, blue: 0.847, alpha: 1)
    public static let surfaceWhiteHighlight = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1)
    public static let typographyBaseFont = System /* Main font used in this category */
    public static let typographyBaseFontFamily = system, -apple-system, ".SFNSText-Regular", "San Francisco", "Roboto", "Oxygen-Sans", "Ubuntu", "Cantarell", "Segoe UI", "Helvetica Neue", "Lucida Grande", sans-serif /* The font stack which has fallbacks primarly used on web */
    public static let typographyBaseLetterform = sans-serif /* the letterform type which the font belongs to */
    public static let typographyBrandFont = System /* Main font used in this category */
    public static let typographyBrandFontFamily = system, -apple-system, ".SFNSText-Regular", "San Francisco", "Roboto", "Oxygen-Sans", "Ubuntu", "Cantarell", "Segoe UI", "Helvetica Neue", "Lucida Grande", sans-serif /* The font stack which has fallbacks primarly used on web */
    public static let typographyBrandLetterform = sans-serif /* the letterform type which the font belongs to */
    public static let typographyFontSizeDefault = 16 /* The font-size in px */
    public static let typographyFontSizeRem = 16 /* The font-size in rem */
    public static let typographyFontSizeRoot = 16 /* The browser default font-size */
    public static let typographyFontWeightBlack = 900
    public static let typographyFontWeightBold = 700
    public static let typographyFontWeightExtraBold = 800
    public static let typographyFontWeightLight = 300
    public static let typographyFontWeightMedium = 500
    public static let typographyFontWeightRegular = 400
    public static let typographyFontWeightSemiBold = 600
    public static let typographyMonospaceFontFamily = Consolas, "Andale Mono WT", "Andale Mono", "Lucida Console", "Lucida Sans Typewriter", "DejaVu Sans Mono", "Bitstream Vera Sans Mono", "Liberation Mono", "Nimbus Mono L", Monaco, "Courier New", Courier, monospace
    public static let typographySystemFontFamily = system, -apple-system, ".SFNSText-Regular", "San Francisco", "Roboto", "Oxygen-Sans", "Ubuntu", "Cantarell", "Segoe UI", "Helvetica Neue", "Lucida Grande", sans-serif
}
